name: Publish New Version
on: [push]
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        binary_name: "iamthat"
        extra_files: README.md
        