on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1' # The Go version to download (if necessary) and use.
      - name: Run build for Mac
        run: GOOS=darwin GOARCH=amd64 go build . -o build/iamthat-$GOOS-$GOARCH
        env:
          GOOS: darwin
          GOARCH: amd64
          GO111MODULE: "off"
      - name: Run build for Linux
        run: GOOS=darwin GOARCH=amd64 go build . -o build/iamthat-$GOOS-$GOARCH
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Run build for Windows
        run: GOOS=darwin GOARCH=amd64 go build . -o build/iamthat-$GOOS-$GOARCH
        env:
          GOOS: windows
          GOARCH: amd64
      - uses: "marvinpinto/action-automatic-releases@latest"
        id: create_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "README.md"
      - name: Print output
        run: |
          echo "Output automatic_release_tag ${{ steps.create_release.outputs.automatic_releases_tag }}"
          echo "Output upload_url ${{ steps.create_release.outputs.upload_url }}"
          echo "RELEASE_NAME=$( echo ${{ github.ref }} | grep -o 'v[{0-9}\.]*' )" >> $GITHUB_ENV
      - name: Upload asset to github release page
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/iamthat-$GOOS-$GOARCH
          asset_name: aimthat-$GOOS-$GOARCH-${{ env.RELEASE_NAME }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GOOS: darwin
          GOARCH: amd64

