on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1' # The Go version to download (if necessary) and use.
      - name: Run build
        run: go build .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: github.event.commits[0].message
          draft: false
          prerelease: false
      - name: Print output
        run: |
          echo "Output automatic_release_tag ${{ steps.create_release.outputs.automatic_releases_tag }}"
          echo "Output upload_url ${{ steps.create_release.outputs.upload_url }}"
      - name: Upload asset to github release page
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./iamthat
          asset_name: aimthat-${{ github.ref }}
          asset_content_type: application/octet-stream
